Repository phdljr/one-click-recipe, pull requests merged in 2024-01, with the labels that each got.

#17 Sample - 예시 코드 수정
  src/main/java/org/springeel/oneclickrecipe/sample/service/impl/TestServiceImpl.java
Labels: refactor, idea

#20 Feature/custom exception - 커스텀 예외 처리 규격 설정
  src/main/java/org/springeel/oneclickrecipe/global/exception/CustomException.java
  src/main/java/org/springeel/oneclickrecipe/global/exception/ErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/org/springeel/oneclickrecipe/sample/controller/TestController.java
  src/main/java/org/springeel/oneclickrecipe/sample/exception/AlreadyExistsTestException.java
  src/main/java/org/springeel/oneclickrecipe/sample/exception/ForbiddenAccessTestException.java
  src/main/java/org/springeel/oneclickrecipe/sample/exception/NotFoundTestException.java
  src/main/java/org/springeel/oneclickrecipe/sample/exception/TestErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/sample/service/impl/TestServiceImpl.java
Labels: feature

#32 [#18]Feat: Spring Security 설정
  src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
Labels: feature

#35 Feature/recipe create
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/mapper/RecipeMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/mapper/dto/RecipeDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/mapper/entity/RecipeEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/RecipeService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
Labels: feature, refactor

#39 Feature/order list - 주문 목록 조회 기능 구현 #14
  src/main/java/org/springeel/oneclickrecipe/domain/order/controller/OrderController.java
  src/main/java/org/springeel/oneclickrecipe/domain/order/dto/service/OrderReadResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/order/mapper/entity/OrderEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/order/repository/OrderRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/order/service/OrderService.java
  src/main/java/org/springeel/oneclickrecipe/domain/order/service/impl/OrderServiceImpl.java
Labels: feature

#38 Feature/recipe delete
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/controller/RecipeDeleteControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/service/RecipeDeleteServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/entity/Recipe.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/exception/AlreadyExistsRecipeException.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/exception/ForbiddenAccessRecipeException.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/exception/NotFoundRecipeException.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/exception/RecipeErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/mapper/dto/RecipeDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/repository/RecipeRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/RecipeService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
Labels: feature

#44 Feature/user login - 커스텀 예외 핸들러 추가 & 유저 로그인 & 회원가입 기능 구현
  src/main/java/org/springeel/oneclickrecipe/domain/user/controller/UserController.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/controller/UserLoginControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/controller/UserSignUpControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/service/UserLoginServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/service/UserSignUpServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/exception/AlreadyExistsEmailException.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/exception/DuplicateNicknameException.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/exception/NotFoundUserException.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/exception/NotMatchPasswordException.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/exception/UserErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/dto/UserDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/entity/EncodePassword.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/entity/PasswordTranslator.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/entity/UserEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/repository/UserRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/LoginServletService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/UserService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/impl/LoginServletServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/impl/UserServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
  src/main/java/org/springeel/oneclickrecipe/global/exception/dto/CustomExceptionResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/global/exception/handler/GlobalExceptionHandler.java
Labels: feature, refactor

#52 Feature/recipeprocess 레시피_조리과정 기능구현을 위한 기본 패키지들 생성
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/controller/RecipeProcessController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/controller/RecipeProcessCreateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/service/RecipeProcessCreateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/mapper/dto/RecipeProcessDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/mapper/entity/RecipeProcessEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/repository/RecipeProcessRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/RecipeProcessService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/impl/RecipeProcessServiceImpl.java
Labels: feature

#58 Feature/recipeprocess delete 레시피_조리과정 삭제 기능 추가
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/controller/RecipeProcessController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/controller/RecipeProcessCreateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/service/RecipeProcessCreateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/entity/RecipeProcess.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/exception/AlreadyExistsRecipeProcessException.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/exception/ForbiddenAccessRecipeProcessException.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/exception/NotFoundRecipeProcessException.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/exception/RecipeProcessErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/mapper/dto/RecipeProcessDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/mapper/entity/RecipeProcessEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/repository/RecipeProcessRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/RecipeProcessService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/impl/RecipeProcessServiceImpl.java
Labels: feature

#60 Feature/recipeprocess update 레시피_조리과정 업데이트 기능 구현
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/controller/RecipeProcessController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/controller/RecipeProcessUpdateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/service/RecipeProcessUpdateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/entity/RecipeProcess.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/mapper/dto/RecipeProcessDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/RecipeProcessService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/impl/RecipeProcessServiceImpl.java
Labels: feature

#64 Refactor: 레시피 삭제 기능 코드 리팩토링
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/controller/RecipeDeleteControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/service/RecipeDeleteServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/mapper/dto/RecipeDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/RecipeService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
Labels: refactor

#65 Feature/review delete - 후기 삭제 기능 구현 & 후기 수정 기능 수정
  src/main/java/org/springeel/oneclickrecipe/domain/review/controller/ReviewController.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/dto/controller/ReviewDeleteControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/dto/service/ReviewDeleteServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/mapper/dto/ReviewDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/mapper/entity/ReviewEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/service/ReviewService.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImpl.java
Labels: feature

#68 Feature/cors - CORS 설정
  src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
Labels: feature

#69 Feature/recipefood
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/dto/controller/RecipeFoodCreateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/dto/service/RecipeFoodCreateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/mapper/dto/RecipeFoodDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/mapper/service/RecipeFoodServiceMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/repository/RecipeFoodRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/service/RecipeFoodService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/service/impl/RecipeFoodServiceImpl.java
Labels: feature

#81 Add files via upload - README에 쓸 이미지 업로드
  딸깍 이미지.png
  애자일선언.png
Labels: feature

#82 Docs: README.md 작성
  README.md
Labels: feature

#71 Feature/recipefood create
  src/main/java/org/springeel/oneclickrecipe/domain/food/exception/AlreadyExistsFoodException.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/exception/FoodErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/exception/ForbiddenAccessFoodException.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/exception/NotFoundFoodException.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/repository/FoodRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/controller/RecipeFoodController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/dto/controller/RecipeFoodCreateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/dto/service/RecipeFoodCreateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/entity/RecipeFood.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/mapper/dto/RecipeFoodDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/mapper/service/RecipeFoodEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/mapper/service/RecipeFoodServiceMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/service/RecipeFoodService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/service/impl/RecipeFoodServiceImpl.java
Labels: feature

#85 Feature/s3 file save
  src/main/java/org/springeel/oneclickrecipe/global/config/S3Config.java
  src/main/java/org/springeel/oneclickrecipe/global/util/S3Provider.java
Labels: feature, refactor

#92 Feature/like/create - 레시피 좋아요 추가 기능 구현
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/controller/RecipeLikeController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/entity/RecipeLike.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/entity/RecipeLikeId.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/exception/AlreadyExistsRecipeLikeException.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/exception/NotFoundRecipeLikeException.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/exception/RecipeLikeErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/mapper/dto/RecipeLikeDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/mapper/entity/RecipeLikeEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/repository/RecipeLikeRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/service/RecipeLikeService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/service/impl/RecipeLikeServiceImpl.java
Labels: feature

#96 Feature/cart/delete - 장바구니 초기화 기능 구현
  src/main/java/org/springeel/oneclickrecipe/domain/cart/controller/CartController.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/exception/AlreadyExistsCartException.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/exception/CartErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/exception/ForbiddenAccessCartException.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/exception/NotFoundCartException.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/repository/CartRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/service/CartService.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/service/impl/CartServiceImpl.java
Labels: feature

#99 feature: S3에 저장된 파일 삭제 기능 구현
  src/main/java/org/springeel/oneclickrecipe/global/util/S3Provider.java
Labels: feature, style

#106 Feature/cart/create - 장바구니 아이템 추가 기능 구현
  src/main/java/org/springeel/oneclickrecipe/domain/cart/controller/CartController.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/dto/controller/CartAddControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/dto/service/CartAddServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/mapper/dto/CartDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/repository/CartRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/service/CartService.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/service/impl/CartServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/repository/RecipeFoodRepository.java
Labels: feature

#116 Refactor/recipeprocess update
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/controller/RecipeProcessController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/RecipeProcessService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/impl/RecipeProcessServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/global/util/S3Provider.java
Labels: refactor

#120 Feature/review/get
  src/main/java/org/springeel/oneclickrecipe/domain/review/controller/ReviewController.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/dto/service/ReviewReadResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/repository/ReviewRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/service/ReviewService.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImpl.java
Labels: feature

#124 Feature/security - Bean Validation & Security 인가 설정
  .gitignore
  src/main/java/org/springeel/oneclickrecipe/domain/payment/service/impl/PaymentServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/controller/UserController.java
  src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
Labels: feature

#135 Feature/review/get
  src/main/java/org/springeel/oneclickrecipe/domain/review/controller/ReviewController.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/dto/controller/ReviewCreateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/dto/controller/ReviewDeleteControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/dto/controller/ReviewUpdateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/dto/service/ReviewDeleteServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/mapper/dto/ReviewDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImpl.java
  src/test/java/org/springeel/oneclickrecipe/domain/order/service/impl/OrderServiceImplTest.java
  src/test/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImplTest.java
Labels: feature

#134 feat/security - /api/v1/recipes/{recipeId}/reviews 인가 작업 추가
  src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
Labels: feature

#129 [#125]Feat: Bean Validation handler 추가
  src/main/java/org/springeel/oneclickrecipe/global/exception/dto/BeanValidationExceptionResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/global/exception/dto/FieldErrorResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/global/exception/handler/GlobalExceptionHandler.java
Labels: feature

#138 Refactor/recipeprocess create
  src/main/java/org/springeel/oneclickrecipe/domain/cart/service/impl/CartServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/dto/FoodReadResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/entity/Food.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/mapper/FoodEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/controller/RecipeFoodController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/dto/service/RecipeFoodReadResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/entity/RecipeFood.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/mapper/service/RecipeFoodEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/repository/RecipeFoodRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/service/RecipeFoodService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/service/impl/RecipeFoodServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/impl/RecipeProcessServiceImpl.java
Labels: refactor

#153 Refactor: cart 수정
  src/main/java/org/springeel/oneclickrecipe/domain/cart/service/impl/CartServiceImpl.java
Labels: feature

#157 Refactor/recipe
  src/main/java/org/springeel/oneclickrecipe/domain/cart/service/impl/CartServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/service/response/RecipeAllReadResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/service/response/RecipeReadResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/mapper/entity/RecipeEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/RecipeService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/controller/RecipeFoodController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/entity/RecipeFood.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/mapper/service/RecipeFoodEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/repository/RecipeFoodRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/service/RecipeFoodService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/service/impl/RecipeFoodServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/entity/RecipeLike.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/controller/RecipeProcessController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/entity/RecipeProcess.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/mapper/entity/RecipeProcessEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/repository/RecipeProcessRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/RecipeProcessService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/impl/RecipeProcessServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/entity/Review.java
  src/main/java/org/springeel/oneclickrecipe/global/util/S3Provider.java
Labels: feature, refactor

#158 Feature/orderdetail/unit - OrderDetail unit 필드 추가
  src/main/java/org/springeel/oneclickrecipe/domain/orderdetail/entity/OrderDetail.java
  src/main/java/org/springeel/oneclickrecipe/domain/orderdetail/mapper/entity/OrderDetailEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/payment/service/impl/PaymentServiceImpl.java
Labels: feature

#159 Refactor/deploy - plain.jar 생성 방지
  build.gradle
  src/test/java/org/springeel/oneclickrecipe/OneClickRecipeApplicationTests.java
  src/test/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImplTest.java
Labels: chore

#163 Refactor: Subscrive -> Follow 명칭 변경
  src/main/java/org/springeel/oneclickrecipe/domain/follow/entity/Follow.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/entity/FollowId.java
Labels: refactor

#136 Test: 장바구니 아이템 조회 테스트
  src/test/java/org/springeel/oneclickrecipe/domain/order/service/OrderServiceCreateTest.java
Labels: test

#173 Test - 주문 파트 테스트 코드 작성
  src/test/java/org/springeel/oneclickrecipe/domain/order/service/OrderServiceCreateTest.java
Labels: test

#171 Refactor : 불필요한 예외처리 삭제
  src/main/java/org/springeel/oneclickrecipe/domain/cart/exception/AlreadyExistsCartException.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/exception/CartErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/exception/ForbiddenAccessCartException.java
  src/main/java/org/springeel/oneclickrecipe/domain/cart/exception/NotFoundCartException.java
Labels: refactor

#180 Feature/food read all
  src/main/java/org/springeel/oneclickrecipe/domain/cart/entity/Cart.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/controller/FoodController.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/dto/controller/FoodCreateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/dto/controller/FoodUpdateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/dto/service/request/FoodCreateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/dto/service/request/FoodUpdateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/dto/service/response/FoodReadAllServiceResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/entity/Food.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/mapper/dto/FoodDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/mapper/service/FoodEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/service/FoodService.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/service/impl/FoodServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/entity/RecipeFood.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/exception/UserErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/repository/UserRepository.java
  src/test/java/org/springeel/oneclickrecipe/domain/food/service/impl/FoodServiceImplTest.java
Labels: feature

#182 Feature/follow/create
  src/main/java/org/springeel/oneclickrecipe/domain/follow/controller/FollowController.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/exception/AlreadyExistsFollowException.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/exception/FollowErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/exception/NotFoundFollowException.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/mapper/entity/FollowEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/repository/FollowRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/service/FollowService.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/service/impl/FollowServiceImpl.java
Labels: feature

#184 Feature/follow/delete
  src/main/java/org/springeel/oneclickrecipe/domain/follow/controller/FollowController.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/entity/Follow.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/entity/FollowId.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/repository/FollowRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/service/FollowService.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/service/impl/FollowServiceImpl.java
Labels: feature

#185 Feature/follow/delete
  src/main/java/org/springeel/oneclickrecipe/domain/follow/exception/FollowErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/exception/NotFollowSelfException.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/service/impl/FollowServiceImpl.java
Labels: refactor

#188 Feature/order/refactor - Recipe 생성 로직 수정
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/controller/RecipeCreateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/service/response/RecipeReadResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/entity/Recipe.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/mapper/entity/RecipeEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/RecipeService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/controller/RecipeFoodController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/mapper/dto/RecipeFoodDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/service/RecipeFoodService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/service/impl/RecipeFoodServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/controller/RecipeProcessCreateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/controller/RecipeProcessUpdateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/service/request/RecipeProcessCreateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/service/request/RecipeProcessUpdateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/service/response/RecipeProcessReadResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/entity/RecipeProcess.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/mapper/dto/RecipeProcessDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/impl/RecipeProcessServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/global/util/S3Provider.java
Labels: feature, refactor

#187 Feature/admin - 관리자 기능 구현
  src/main/java/org/springeel/oneclickrecipe/domain/admin/controller/AdminController.java
  src/main/java/org/springeel/oneclickrecipe/domain/admin/dto/UserRoleUpdateRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/admin/service/AdminService.java
  src/main/java/org/springeel/oneclickrecipe/domain/admin/service/impl/AdminServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/entity/User.java
  src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
Labels: feature

#190 Feature/kakao login - 카카오 로그인 API 연동
  .gitignore
  src/main/java/org/springeel/oneclickrecipe/domain/user/controller/KakaoController.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/controller/UserController.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/kakao/KakaoUserInfoDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/KakaoService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/LoginServletService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/impl/LoginServletServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
  src/test/java/org/springeel/oneclickrecipe/domain/food/service/impl/FoodServiceImplTest.java
  src/test/java/org/springeel/oneclickrecipe/domain/order/service/OrderServiceCreateTest.java
  src/test/resources/application.yml
Labels: feature

#191 feature: review 작성자 닉네임 추가
  src/main/java/org/springeel/oneclickrecipe/domain/review/dto/service/response/ReviewReadResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/mapper/entity/ReviewEntityMapper.java
Labels: feature

#192 Feature/exception/handler - ExceptionHandler 수정 및 RefreshToken 추가
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/impl/RecipeProcessServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/controller/KakaoController.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/controller/UserController.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/KakaoService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/LoginServletService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/UserService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/impl/LoginServletServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/impl/UserServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
  src/main/java/org/springeel/oneclickrecipe/global/filter/ExceptionHandlerFilter.java
  src/main/java/org/springeel/oneclickrecipe/global/filter/JwtAuthorizationFilter.java
  src/main/java/org/springeel/oneclickrecipe/global/jwt/JwtStatus.java
  src/main/java/org/springeel/oneclickrecipe/global/jwt/JwtUtil.java
  src/main/java/org/springeel/oneclickrecipe/global/jwt/exception/BadRefreshTokenException.java
  src/main/java/org/springeel/oneclickrecipe/global/jwt/exception/JwtErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/global/s3/S3Provider.java
  src/main/java/org/springeel/oneclickrecipe/global/util/JwtUtil.java
  src/test/resources/application.yml
Labels: feature

#194 Feature/like/read - 좋아요 조회 기능 구현
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/controller/RecipeLikeController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/repository/RecipeLikeRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/service/RecipeLikeService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/service/impl/RecipeLikeServiceImpl.java
Labels: feature

#195 Feature/user/refresh - 로그인, 카카오 로그인, 토큰 재발급 API 호출 시, LoginDto 반환
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/service/response/RecipeAllReadResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/controller/KakaoController.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/controller/UserController.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/service/request/UserLoginServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/service/request/UserSignUpServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/service/response/UserLoginResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/dto/UserDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/entity/UserEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/KakaoService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/UserService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/impl/UserServiceImpl.java
Labels: feature

#197 Feature/follow/read
  src/main/java/org/springeel/oneclickrecipe/domain/follow/controller/FollowController.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/repository/FollowRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/service/FollowService.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/service/impl/FollowServiceImpl.java
Labels: feature

#200 refactor: 로직 변경 및 변수명 수정
  src/main/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImpl.java
Labels: refactor

#208 Feat: 식재료 GET API -> 이름순으로 내림차순
  src/main/java/org/springeel/oneclickrecipe/domain/follow/controller/FollowController.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/entity/Follow.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/entity/FollowId.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/exception/NotFollowSelfException.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/mapper/entity/FollowEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/repository/FollowRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/service/FollowService.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/controller/FoodController.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/service/FoodService.java
  src/main/java/org/springeel/oneclickrecipe/domain/food/service/impl/FoodServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/order/service/impl/OrderServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/entity/Recipe.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/mapper/service/RecipeFoodEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/repository/RecipeFoodRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipefood/service/RecipeFoodService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/controller/UserController.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/repository/UserRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/KakaoService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/UserService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/impl/UserServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/global/config/WebSecurityConfig.java
  src/main/java/org/springeel/oneclickrecipe/global/filter/JwtAuthorizationFilter.java
  src/main/java/org/springeel/oneclickrecipe/global/jwt/JwtUtil.java
  src/main/java/org/springeel/oneclickrecipe/global/jwt/exception/JwtErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/global/s3/S3Provider.java
Labels: feature

#206 Feature/update/nickname - 닉네임변경기능구현
  src/main/java/org/springeel/oneclickrecipe/domain/user/controller/UserController.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/controller/NicknameUpdateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/service/request/NicknameUpdateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/entity/User.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/exception/ForbiddenAccessNicknameException.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/exception/UserErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/dto/UserDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/repository/UserRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/UserService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/impl/UserServiceImpl.java
Labels: feature

#209 Feature/update/password
  src/main/java/org/springeel/oneclickrecipe/domain/user/controller/UserController.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/controller/PasswordUpdateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/service/request/PasswordUpdateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/entity/User.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/exception/UserErrorCode.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/dto/UserDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/UserService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/impl/UserServiceImpl.java
Labels: refactor

#210 Feat: Review 생성 DTO 추가
  src/main/java/org/springeel/oneclickrecipe/domain/review/controller/ReviewController.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/dto/service/response/ReviewCreateResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/mapper/entity/ReviewEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/service/ReviewService.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImpl.java
Labels: feature

#214 Feat: 무한 스크롤 레시피 조회용 Slice 추가
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/repository/RecipeRepository.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/RecipeService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/sample/controller/TestController.java
  src/main/java/org/springeel/oneclickrecipe/sample/repository/TestRepository.java
  src/main/java/org/springeel/oneclickrecipe/sample/service/TestService.java
  src/main/java/org/springeel/oneclickrecipe/sample/service/impl/TestServiceImpl.java
Labels: feature

#215 refactor: 구독 기능을 레시피 단건조회에서 수행하기 위한 리팩토링
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/service/response/RecipeReadResponseDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/RecipeService.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
Labels: refactor
