Repository phdljr/one-click-recipe, pull requests merged in 2024-02, with the labels that each got.

#217 refactor: intro 추가
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
Labels: refactor

#219 Refactor: RecipeLike 조회 로직 수정
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/entity/Recipe.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/entity/RecipeLike.java
Labels: refactor

#221 refactor: RecipeController update 기능
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
Labels: refactor

#222 Feature/user/delete - 회원탈퇴기능
  src/main/java/org/springeel/oneclickrecipe/domain/cart/entity/Cart.java
  src/main/java/org/springeel/oneclickrecipe/domain/follow/entity/Follow.java
  src/main/java/org/springeel/oneclickrecipe/domain/order/entity/Order.java
  src/main/java/org/springeel/oneclickrecipe/domain/payment/entity/Payment.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/entity/Recipe.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipelike/entity/RecipeLike.java
  src/main/java/org/springeel/oneclickrecipe/domain/review/entity/Review.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/controller/UserController.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/controller/DeleteUserControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/dto/service/request/DeleteUserServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/dto/UserDtoMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/mapper/entity/UserEntityMapper.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/UserService.java
  src/main/java/org/springeel/oneclickrecipe/domain/user/service/impl/UserServiceImpl.java
Labels: feature

#225 feature: 이미지 수정을 결정하기 위한 검증 로직 추가
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/controller/RecipeController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/controller/RecipeUpdateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/dto/service/request/RecipeUpdateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipe/service/impl/RecipeServiceImpl.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/controller/RecipeProcessController.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/controller/RecipeProcessUpdateControllerRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/dto/service/request/RecipeProcessUpdateServiceRequestDto.java
  src/main/java/org/springeel/oneclickrecipe/domain/recipeprocess/service/impl/RecipeProcessServiceImpl.java
Labels: feature

#229 Test: 리뷰조회 테스트코드 작성
  src/test/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImplTest.java
Labels: test

#235 Test/review/create - 리뷰작성 테스트코드 작성
  src/test/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImplTest.java
Labels: test

#239 refactor: s3 업데이트 로직 수정
  src/main/java/org/springeel/oneclickrecipe/global/s3/S3Provider.java
Labels: bug, refactor

#240 Test: 리뷰수정 테스트코드 작성
  src/test/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImplTest.java
Labels: test

#244 Test: 리뷰삭제 테스트코드 작성
  src/test/java/org/springeel/oneclickrecipe/domain/review/service/impl/ReviewServiceImplTest.java
Labels: test

#249 Readme - 리드미 수정
  README.md
Labels: feature

#251 feat : 리드미 수정
  README.md
Labels: feature

#252 feat: 깃허브 주소 수정
  README.md
Labels: feature
